version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
